ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE VIEW
TO scott;

GRANT CREATE SYNONYM TO scott;
GRANT CREATE PUBLIC SYNONYM TO scott;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER hr
IDENTIFIED BY hr
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO hr;

