ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER scott
IDENTIFIED BY tiger
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE VIEW
TO scott;

GRANT CREATE SYNONYM TO scott;
GRANT CREATE PUBLIC SYNONYM TO scott;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER hr
IDENTIFIED BY hr
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE
TO hr;

SELECT tablespace_name, bytes/1024/1024 AS MB, file_name
FROM dba_data_files;

ALTER DATABASE DATAFILE 'C:\APP\ADMIN\PRODUCT\21C\ORADATA\XE\USERS01.DBF' AUTOEXTEND ON;